\input texinfo   @c -*-texinfo-*-
@comment $Id@w{$}
@comment %**start of header
@settitle DameLibraries: Using Python Libraries from Tests @value{VERSION}
@syncodeindex pg cp
@comment %**end of header
@include copying-fdl.texi

@titlepage
@title DameLibraries: Using Python Libraries from Tests
@author David Arroyo Men@'endez (@email{davidam@@gmail.com})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Top

DameLibraries: Using Python Libraries from Tests (version @value{VERSION}, @value{UPDATED}).
@end ifnottex

@menu
* Introduction::
* Installation::
* DameNumpy::
* DameNLTK::
* License::
* Index::


@end menu

@node Introduction
@chapter Introduction
@cindex Introduction

Python is a winner in the trend market of programming languages in
this moment. Although the sintaxis is so comfortable to the
programmers, the clue is in the modern libraries for system
administrators, scientifics and with low importance for web
programmers.

You can see the Tiobe Index:

@image{images/tiobeindex2021,6in,,Tiobe Index 2021}

You can check that Python is growing fast and reaching the most
important positions in the market. The third position in January of
2021.

You can use or don't use a test system such as nose or pytest, but all
people need test the code in the programming. After to write software
you must introduce inputs in your code and verify if the output is ok.

The advantage using a test system is generate automation in the
process about inputs, code being tested and outputs. Each test is
evaluated with asserts, that's comparations between the result that
you deserve and the result obtained. For instance,

@example
    def test_models_lda(self):
        X = np.array([[-1, -1], [-2, -1], [-3, -2],
                      [1, 1], [2, 1], [3, 2]])
        y = np.array([1, 1, 1, 2, 2, 2])
        clf = LinearDiscriminantAnalysis()
        clf.fit(X, y)
        self.assertEqual(clf.predict([[-1, -1]]), 1)
@end example

So, assertEqual is the comparision and the rest is the code to be
verified.

To become a professional in Python you must learn a good bunch of
libraries. So you can practice the libraries reading tutorials, python
notebooks, or you could write tests about this libraries and perhaps
to share these tests in some software repository.

If you save all test code about your python libraries in one or
various software repositories you can test all code with a
command. The python libraries can suffer chances, but you have the
control about the use that you do about your libraries.

The goal of this book is to teach Python Libraries from the tests.

@node Installation
@chapter Installation
@cindex Installation
@cindex Python Virtual Environment

You can create a python virtual environment and to install
damelibraries with python package:

@example
$ python3 -m venv /tmp/venv
$ cd /tmp/venv
$ source bin/activate
$ pip install --upgrade pip
$ pip3 install damelibraries
$ cd lib/python3.5/site-packages/damelibraries
@end example

Now you can execute tests to check different libraries:

@example
$ cd /tmp/venv/lib/python3.8/site-packages/damealgorithms
$ nosetests3 tests

$ cd /tmp/venv/lib/python3.8/site-packages/damejson
$ nosetests3 tests

$ cd /tmp/venv/lib/python3.8/site-packages/damenltk
$ nosetests3 tests

$ cd /tmp/venv/lib/python3.8/site-packages/damenumpy
$ nosetests3 tests

$ cd /tmp/venv/lib/python3.8/site-packages/damepandas
$ nosetests3 tests

$ cd /tmp/venv/lib/python3.8/site-packages/damescikit
$ nosetests3 tests

$ cd /tmp/venv/lib/python3.8/site-packages/damescipy
$ nosetests3 tests
@end example

@node DameNumpy
@chapter DameNumpy
@cindex DameNumpy

Numpy is a library about algebra used as dependency in a lot of python
programs. We have classified the tests in basics, datatypes and
maths. Basics is related to the most common uses about the library
(sum vectors, transpose matrix, generate eye matrix, ...). Datatypes
is about specific uses about the numpy datatypes that perhaps you need
practice more. And maths is about maths operations. You can execute
the test with:

@example
$ cd /tmp/venv/lib/python3.8/site-packages/damenumpy
$ nosetests3 tests/test_basics.py
$ nosetests3 tests/test_datatypes.py
$ nosetests3 tests/test_maths.py
@end example

@node DamePandas
@chapter DamePandas
@cindex DamePandas

Pandas is a fast, powerful, flexible and easy to use open source data
analysis and manipulation tool, built on top of the Python programming
language.

@example
$ cd /tmp/venv/lib/python3.8/site-packages/damepandas
$ nosetests3 test/test_create.py
$ nosetests3 test/test_json.py
$ nosetests3 test/test_operators.py
$ nosetests3 test/test_utils.py
@end example

In test_create.py is being created tests for create datastructures.
In test_json.py we practice some json utils in Pandas.  In
test_operators.py and test_utils.py there are more functions related
to Pandas such as read_csv, concat, shape, ...


@node DameNLTK
@chapter DameNLTK
@cindex DameNLTK

NLTK is an acronym about Natural Language ToolKit.

A summary of tasks about Natural Language Processing could be:

@itemize @bullet
@item
Sentiment Analysis
@item
Detect Gender
@item
Sentence Similarity
@item
Text Summary
@item
Classify Documents
@item
Manage Words
@item
Gramatical Trees
@item
Extract Keywords
@item
Disambiguation
@end itemize

You could be in the path of nltk so:

@example
$ cd /tmp/venv/
$ source bin/activate
(venv)$ pip3 install damenltk
$ cd /tmp/venv/lib/python3.8/site-packages/damenltk
$ nosetest3 test
@end example

@section Sentiment Analysis

Sentiment analysis is applied in a popular way in Twitter with python
libraries such as tweepy. Finally, it is a classification task about
words with a label (the sentiment). That could be implemented with
nltk. Take a look to the test:

@example
import unittest
from nltk.classify import SklearnClassifier
class TddInPythonExample(unittest.TestCase):

    def test_sentiment_variable_create_returns_correct_result(self):
        pos_tweets = [('I love this car', 'positive'),
                      ('This view is amazing', 'positive'),
                      ('I feel great this morning', 'positive'),
                      ('I am so excited about the concert', 'positive'),
                      ('He is my best friend', 'positive'),
                      ('This movie was great', 'positive'),
                      ('This movie was not pathetic', 'positive')]

        neg_tweets = [('I do not like this car', 'negative'),
                      ('This view is horrible', 'negative'),
                      ('I feel tired this morning', 'negative'),
                      ('I am not looking forward to the concert', 'negative'),
                      ('He is my enemy', 'negative'),
                      ('This is a pathetic movie', 'negative')]

        tweets_with_sentiment = []
        for (tweet, sentiment) in pos_tweets + neg_tweets:
            filtered_tweet_words = [word.lower() for word in tweet.split() if len(word) >= 3]
            tweets_with_sentiment.append((filtered_tweet_words, sentiment))

        self.assertEqual([(['love', 'this', 'car'], 'positive'),
                          (['this', 'view', 'amazing'], 'positive'),
                          (['feel', 'great', 'this', 'morning'], 'positive'),
                          (['excited', 'about', 'the', 'concert'], 'positive'),
                          (['best', 'friend'], 'positive'),
                          (['this', 'movie', 'was', 'great'], 'positive'),
                          (['this', 'movie', 'was', 'not', 'pathetic'], 'positive'),
                          (['not', 'like', 'this', 'car'], 'negative'),
                          (['this', 'view', 'horrible'], 'negative'),
                          (['feel', 'tired', 'this', 'morning'], 'negative'),
                          (['not', 'looking', 'forward', 'the', 'concert'], 'negative'),
                          (['enemy'], 'negative'),
                          (['this', 'pathetic', 'movie'], 'negative')],
                          tweets_with_sentiment)
@end example

You can execute this test with:

@example
$ nosetest3 test/test_sentiment.py
@end example

@section Detect Gender

The gender detection from the name is a NLP task. So the input is one
or more word (name and perhaps surname) and the output is a gender
male, female, ...

NLTK brings a good list of names in the nltk.corpus. So you can
classify names with two ways:

@itemize @bullet
@item
Querying single files
@item
Supervised classifier
@end itemize

The python method using single files would be:

@example
    def gender_name(self, name):
        gender = 'undefined'
        if name in names.words('male.txt'):
            gender = 'male'
        if name in names.words('female.txt'):
            if (gender == 'male'):
                gender = 'both'
            else:
                gender = 'female'
        return gender
@end example

And the python test would be:

@example
    def test_gender_name_method_returns_correct_result(self):
        dn = DameNLTK()
        self.assertTrue(dn.gender_name("Neo"), "male")
        self.assertTrue(dn.gender_name("Trinity"), "female")
        self.assertTrue(dn.gender_name("Andrea"), "both")                
@end example

The python methods using machine learnig would be:

@example
    def gender_features(self, word):
        return {'last_letter': word[-1]}
    
    def gender_classifier(self):
        labeled_names = ([(name, 'male') for name in names.words('male.txt')] +
                         [(name, 'female') for name in names.words('female.txt')])

        featuresets = [(self.gender_features(n), gender) for (n, gender) in labeled_names]
        train_set, test_set = featuresets[500:], featuresets[:500]
        classifier = nltk.NaiveBayesClassifier.train(train_set)
        return classifier
@end example

And the python tests would be:

@example
    def test_gender_classifier_method_returns_correct_result(self):
        dn = DameNLTK()
        classifier = dn.gender_classifier()
        self.assertTrue(classifier.classify(dn.gender_features("Neo")), "male")
        self.assertTrue(classifier.classify(dn.gender_features("Trinity")), "female")        
@end example

You can use an advanced software to detect gender such as Damegender
with many features:

@example
$ pip3 install damegender[all]
@end example

You can learn to use the software with tests oriented to the user
(bash files) or tests oriented to the developer (python tests). 

@example
$ python3 -m venv /tmp/damegender/
$ cd /tmp/damegender/
$ source bin/activate
$ pip3 install damegender[all]
$ ./testsbycommands.sh 
maindavid test is ok
mainjesus test is ok
mainines test is ok
mainalex test is ok
mainandrea test is ok
mainjesusmaria test is ok
mainjosemaria test is ok
mainelenaluciahelena test is ok
mainjuliaus test is ok
mainjuliauk test is ok
mainjuliauy test is ok
[...]

$ nosetest3 test
[...]
@end example

Execute these tests could be long time, but you can execute a single
file test, for example, you can execute test/test_dame_utils.py:

@example
$ nosetest3 test/test_dame_utils.py
@end example

Or you can execute a single test in a file with:

@example
$ nosetests3 test/test_dame_utils.py:TddInPythonExample.test_string2array
@end example

@section Sentence Similarity

Remembering to W H Gomaa and A A Fahmy in ``A Survey of Text Similarity
Approaches'':

Finding similarity between words is a fundamental part of
text similarity which is then used as a primary stage for sentence,
paragraph and document similarities. Words can be similar in two ways
lexically and semantically. Words are similar lexically if they have a
similar character sequence. Words are similar semantically if they
have the same thing, are opposite of each other, used in the same way,
used in the same context and one is a type of another.

In the python method sentence_similarity we apply similarity
lexical. So, it's dividing the text in two vectors (vector1 and vector2)
and we apply the cosine distance:

@example
    def sentence_similarity(self, sent1, sent2, stopwords=None):
        if stopwords is None:
            stopwords = []

        sent1 = [w.lower() for w in sent1]
        sent2 = [w.lower() for w in sent2]

        all_words = list(set(sent1 + sent2))

        vector1 = [0] * len(all_words)
        vector2 = [0] * len(all_words)

        # build the vector for the first sentence
        for w in sent1:
            if w in stopwords:
                continue
            vector1[all_words.index(w)] += 1

        # build the vector for the second sentence
        for w in sent2:
            if w in stopwords:
                continue
            vector2[all_words.index(w)] += 1

        return 1 - cosine_distance(vector1, vector2)
@end example

We can learn to use this method checking the test:

@example
    def test_sentencesimilarity_method_returns_correct_result(self):
        dn = DameNLTK()
        self.assertTrue(dn.sentence_similarity("This is a good sentence".split(), "This is a bad sentence".split()) > 0.6)
@end example

Remember execute the test to learn if the test is running:

@example
$ nosetest3 test/test_sentence_similarity.py
@end example

@section Singulars and Plurals

@section Stopwords

For some search engines, these are some of the most common, short
function words, such as the, is, at, which, and on. In this case, stop words
can cause problems when searching for phrases that include them

You can find the test:

@example
$ nosetest3 test/test_stopwords.py
@end example

@section Manage words

Managing words is about definitions, singulars, plurals, synonims and
antonims

We can start building singulars and plurals from a word. You can read
the test file:

@example
import unittest
import nltk
from nltk.stem import *
from nltk.stem.snowball import SnowballStemmer

class TddInPythonExample(unittest.TestCase):

    def test_stem_returns_correct_result(self):
        stemmer = PorterStemmer()
        self.assertEqual(stemmer.stem("vuelos"), "vuelo")

    def test_snowball_stem_returns_correct_result(self):
        sb = SnowballStemmer("english").stem("generously")
        self.assertEqual(sb, "generous")
@end example

You can test it with:

@example
$ nosetest3 test/test_stem.py
@end example

Another tool for NLP tasks is to retrieve synonims and antonims from
words. You can execute the tests:

@example
$ nosetest3 test/test_syn.py
@end example

Another way is using wordnet:

@example
$ nosetests3 test/test_wordnet.py
@end example

Wordnet provides measures about semantic similarity between
words, definitions about words, ...

@section Corpus

The corpus allows use data very useful in NLP (ex: gutemberg files,
twitter examples, wordnet, names with gender, ...)

@example
$ nosetests3 test/test_corpus.py 
$ nosetests3 test/test_gutenberg.py 
@end example


@node License 
@appendix License
@cindex License

@include fdl-1.3.texi


@node Index
@unnumbered Index
@printindex cp

@bye
